### 
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "gunn",
  "password": "gunn123"
}



###
GET http://127.0.0.1:8000/api/appointments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5Nzc5OTU1LCJpYXQiOjE3Njk3Nzk2NTUsImp0aSI6ImQ3Y2U1NzVkMTI4MzQ4ODk4NGUzNGE0ODIwZDU5OTlhIiwidXNlcl9pZCI6IjEifQ.LWwv3jSUbsqT4ET1Aja7UyVvHdk9W_uLqikFc6R2QuM



### 
POST http://127.0.0.1:8000/api/appointments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5Nzc5OTU1LCJpYXQiOjE3Njk3Nzk2NTUsImp0aSI6ImQ3Y2U1NzVkMTI4MzQ4ODk4NGUzNGE0ODIwZDU5OTlhIiwidXNlcl9pZCI6IjEifQ.LWwv3jSUbsqT4ET1Aja7UyVvHdk9W_uLqikFc6R2QuM
Content-Type: application/json

{
  "doctor": 2,
  "appointment_date": "2026-02-01T10:00:00",
  "status": "SCHEDULED"
}



### 
GET http://127.0.0.1:8000/api/treatments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5Nzc5OTU1LCJpYXQiOjE3Njk3Nzk2NTUsImp0aSI6ImQ3Y2U1NzVkMTI4MzQ4ODk4NGUzNGE0ODIwZDU5OTlhIiwidXNlcl9pZCI6IjEifQ.LWwv3jSUbsqT4ET1Aja7UyVvHdk9W_uLqikFc6R2QuM



### 
POST http://127.0.0.1:8000/api/prescriptions/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5Nzc5OTU1LCJpYXQiOjE3Njk3Nzk2NTUsImp0aSI6ImQ3Y2U1NzVkMTI4MzQ4ODk4NGUzNGE0ODIwZDU5OTlhIiwidXNlcl9pZCI6IjEifQ.LWwv3jSUbsqT4ET1Aja7UyVvHdk9W_uLqikFc6R2QuM
Content-Type: application/json

{
  "appointment": 1,
  "treatment_ids": [1, 2],
  "notes": "Take medicines after meals"
}



### 
GET http://127.0.0.1:8000/api/prescriptions/?appointment=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5Nzc5OTU1LCJpYXQiOjE3Njk3Nzk2NTUsImp0aSI6ImQ3Y2U1NzVkMTI4MzQ4ODk4NGUzNGE0ODIwZDU5OTlhIiwidXNlcl9pZCI6IjEifQ.LWwv3jSUbsqT4ET1Aja7UyVvHdk9W_uLqikFc6R2QuM
